const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 18,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 125,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 20,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 115,
      countInStock: 5,
      brand: "Nike",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 112,
      countInStock: 9,
      brand: "Puma",
      rating: 3.5,
      numReviews: 12,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pants",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 0,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 19,
      description: "high quality product",
    },
  ],
};

export default data;
